
from pprint import pprint
from grim.markov import Markov

big_pile_o_text =\
"""
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur ex eros, semper ut faucibus nec, finibus id neque. Nunc et scelerisque ligula. Etiam in consequat nibh. Fusce nec quam ut purus volutpat auctor. Mauris pellentesque congue leo, a mollis magna dignissim id. Etiam molestie lorem ac luctus rhoncus. Praesent gravida volutpat lorem a consectetur. Sed in mollis dui. Donec faucibus elit sit amet libero condimentum lobortis. Proin efficitur gravida risus, at mollis nunc mattis eget. Vestibulum dignissim elit eros, sed condimentum lacus fringilla at. Cras sit amet risus magna. Proin efficitur nec arcu vitae ultricies. Duis congue, odio eget lacinia eleifend, odio lectus porta urna, non aliquam erat neque ac nibh. Ut venenatis lacinia mauris.

Etiam sed ante tincidunt, luctus arcu vitae, commodo leo. Donec sodales leo et orci venenatis, eu aliquam dolor tincidunt. In ornare odio sed egestas feugiat. Fusce tempus metus nisl, non vehicula purus imperdiet at. In placerat, mi eu dignissim hendrerit, arcu ligula hendrerit metus, vel facilisis erat velit nec purus. Nunc lacinia, justo tristique gravida sagittis, sapien mi semper lacus, eu dictum purus orci vel diam. Nullam pellentesque, est non tincidunt luctus, ligula sem ullamcorper orci, ac efficitur eros magna in lectus. Pellentesque gravida ex non porttitor porta. Donec est ligula, volutpat a leo et, euismod sagittis dui. Duis commodo posuere iaculis. Nullam sit amet sagittis elit. Nulla convallis leo id urna pharetra, nec tristique eros sodales. Praesent sem nisi, rutrum id turpis eu, mattis fringilla est. Nullam at ex eget dui aliquam fringilla vitae in augue. Integer vel arcu sollicitudin, accumsan justo non, sodales lorem.

Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Nam tempor diam in augue dapibus maximus. Aliquam sit amet rhoncus risus. Curabitur iaculis auctor vestibulum. Morbi ullamcorper sagittis suscipit. Fusce ultrices ex in dapibus auctor. Sed sagittis dolor nisl, at suscipit diam congue ac. Vestibulum dignissim sem quis lacus fermentum, ut vehicula dui tincidunt. Etiam tempor leo non arcu accumsan, ut tincidunt diam pretium. Proin pretium dui sed pellentesque pharetra. Curabitur lobortis ligula magna, ut vehicula dui venenatis non. Vestibulum vulputate justo sapien, nec bibendum metus mattis nec. Sed sit amet urna sed elit efficitur consequat sed non ex. Sed tempus metus laoreet erat condimentum, eget scelerisque neque suscipit.

Donec efficitur cursus tortor, nec fringilla mauris vestibulum nec. Cras et posuere nisl, venenatis maximus est. Suspendisse potenti. Aenean ornare dapibus ligula eget placerat. Integer porta velit vitae placerat auctor. Pellentesque mi quam, porttitor nec elit at, dictum facilisis nisi. Morbi eget condimentum diam. Pellentesque neque risus, maximus consequat nulla at, feugiat molestie nisl. Morbi sed ullamcorper mauris. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris fringilla nisi sit amet quam cursus hendrerit. Praesent eleifend aliquet ex sit amet cursus. Quisque ullamcorper interdum turpis. Donec interdum tincidunt feugiat. Pellentesque dolor felis, ullamcorper quis est id, dignissim eleifend ligula. Duis nec nulla nisi.

Nam pulvinar vitae tortor a lobortis. Cras sed elit efficitur, condimentum purus eu, tempor nisl. Duis quis vestibulum eros, eu lobortis diam. Nunc a urna sapien. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc orci elit, ullamcorper nec nibh et, malesuada consectetur elit. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Etiam a iaculis diam. Ut eleifend metus interdum erat rhoncus, in ultricies nisi ultrices. Donec nec magna ac quam varius sagittis. Ut luctus gravida felis interdum tincidunt.
"""

def test_markov():
    pprint(Markov(big_pile_o_text))
